feat(web): adds verify user check
Bloxico/ase-fe-mono pull request #149
Opened 2021-02-01 01:24 UTC by NemanjaNezic23

@aleksaToljic cekiraj samo da nisam pogresno skapirao story, da nije trebalo ovo sve da se uradi na dodatnoj verify stranici?

2021-02-01 08:33 UTC, aleksaToljic requested changes

2021-02-01 08:33 UTC, aleksaToljic commented on apps/web/src/pages/register/_token.tsx
> +       await Http.auth.enableUser({
Da, ovako nesto treba da se uradi samo na verify/_token.tsx

2021-02-01 10:23 UTC, NemanjaNezic23 commented on apps/web/src/pages/register/_token.tsx
> +       await Http.auth.enableUser({
@aleksaToljic Trebalo bi da je okej sada :)

2021-02-01 13:11 UTC, aleksaToljic requested changes

2021-02-01 13:11 UTC, aleksaToljic commented on apps/web/src/pages/verify/_token.tsx
> +          email: localStorage.getItem('email'),
Email ce biti deprecated, cisto da znas, ako vec nije...

2021-02-01 13:11 UTC, aleksaToljic commented on apps/web/src/pages/verify/_token.tsx
> +        history.push('/')
Ako je success push('/login') a failed neka bude ta ruta

2021-02-01 13:11 UTC, aleksaToljic commented on apps/web/src/pages/verify/_token.tsx
> +        <RegistrationContainer.Provider initialState={{ step: 0 }}>
skini ovaj Registration deo, samo treba da bude loader, mozes cak i da ostavis zauvek da loaduje...

2021-02-01 13:11 UTC, aleksaToljic commented on apps/web/src/Routes.tsx
>    '/verify/',
mozes da skines ovaj iznad tvoje promene `/verify/`

2021-02-01 19:53 UTC, NemanjaNezic23 commented on apps/web/src/pages/verify/_token.tsx
> +          email: localStorage.getItem('email'),
Za sad je endpoint sa mail-om, da ostavim onda token-only ili da bude i dalje sa emailom dok ne postane deprecated?

2021-02-02 17:43 UTC, aleksaToljic commented on apps/web/src/pages/verify/_token.tsx
> +          email: localStorage.getItem('email'),
koliko se secam `localStorage.getItem('email')` nema neku spec funkciju (sluzi da ti zapamti email, kad se loginujes).
Napravi task za BE koji ce da skine taj email, do tada moze task da bude inProgress

2021-02-02 17:50 UTC, aleksaToljic approved these changes

2021-02-02 17:52 UTC, merged